config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: [:index , :show]
  root to: 'artists#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    if params[:search].present?
      @artists = SpotifyRuby::Artist.search(params[:search])
    else
      @artists = SpotifyRuby::Artist.search("the")
    end
  end

  def show
    @artist = SpotifyRuby::Artist.find(params[:id])
    @top_tracks = SpotifyRuby::Artist.search_top_tracks_by_artist(params[:id],"US")
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artist/index.html.haml
.row
  - @artists.response.artists.items.each do |artist|
    .col.s12.m4
      .card
        .card-image{style: "height: 350px; overflow: hidden;"}
          = image_tag(artist.images.first.try(:url), style: "" )
          %span.card-title{style: 'text-shadow: 2px 2px #e91e63;'}
            = artist.name
        .card-content{style: "height: 100px;"}
          - artist.genres.each do |genre|
            .chip 
              = genre
          .right
            .chip.green.lighten-3
              +
              = artist.popularity 

        .card-action
          %a{:href => "#"} This is a link

    

app/views/artists/index.html.haml
.row
  = form_tag artists_path, :method => 'get', class: 'col s12' do
    .row
      .input-field.col.s12
        %i.material-icons.prefix search
        %input#icon_prefix.validate{:type => "text", name: :search}
        %label{:for => "icon_prefix"} Artist Name
      / = submit_tag "Search"
      / # = text_field_tag :search, params[:search], id: "icon_prefix"  do
        
.row
  - @artists.response.artists.items.each do |artist|
    .col.s12.m4
      .card
        .card-image{style: "height: 350px; overflow: hidden;"}
          = image_tag(artist.images.first.try(:url), style: "" )
          %span.card-title{style: 'text-shadow: 2px 2px #e91e63;'}
            = artist.name
        .card-content{style: "height: 100px;"}
          - artist.genres.each do |genre|
            .chip 
              = genre
          .right
            .chip.green.lighten-3
              +
              = artist.popularity 

        .card-action
          = link_to "View artist", artist_path(artist.id)

    

app/views/artists/show.html.haml
%h1
  = @artist.response.name
%h3 Top Songs
- @top_tracks.response.tracks.each_with_index do |track, index|
  %h5= "#{index + 1}. #{track.name}"  
  %p
    %audio{:controls => ""}
      %source{:src => "#{track.preview_url}", :type => "audio/ogg"}
      %source{:src => "#{track.preview_url}", :type => "audio/mpeg"}
      %source{:src => "#{track.preview_url}", :type => "audio/wav"}
      Your browser does not support the audio element.

app/views/layouts/_navigation.html.haml
%nav.primary-dark{role: "navigation"}
  .nav-wrapper.container
    = link_to root_path, id: "logo-container", class: 'brand-logo' do
      %span.nav-title
        Fa  + (LaLa)
        %sup 3

    %ul.right.hide-on-med-and-down
      = render 'layouts/navigation_links'
    %ul#nav-mobile.side-nav
      = render 'layouts/navigation_links'
    %a.button-collapse{"data-activates" => "nav-mobile", href: "#"}
      %i.material-icons menu

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Music'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Music'}"}
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container{style: "padding-top: 20px;"}
        = yield